export enum ImageTypes {
  'avif'= 'avif',
  'dz'= 'dz',
  'fits'= 'fits',
  'gif'= 'gif',
  'heif'= 'heif',
  'input'= 'input',
  'jpeg'= 'jpeg',
  'jpg'= 'jpg',
  'jp2'= 'jp2',
  'jxl'= 'jxl',
  'magick'= 'magick',
  'openslide'= 'openslide',
  'pdf'= 'pdf',
  'png'= 'png',
  'ppm'= 'ppm',
  'raw'= 'raw',
  'svg'= 'svg',
  'tiff'= 'tiff',
  'tif'= 'tif',
  'v'= 'v',
  'webp'= 'webp',
}
